---
dataverse:
  endpoint: https://demo.dataverse.org
  token: ac387b5c-0f41-4a75-9285-d88ca0db5446
  dataset_pid: doi:10.70122/FK2/73AJNM
  upload_interval: 3000
vision:
  endpoint: http://127.0.0.1:5000/
  read_interval: 1000